I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    with none
  File "game/script.rpy", line 16, in <module>
    with none
NameError: name 'none' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    with none
  File "H:\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 1651, in execute
    trans = renpy.python.py_eval(self.expr)
  File "H:\Downloads\renpy-8.0.1-sdk\renpy\python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "H:\Downloads\renpy-8.0.1-sdk\renpy\python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    with none
NameError: name 'none' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
trial 1 1.0
Thu Jul 21 18:29:13 2022
